version: '3'
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:3095'
    volumes:
      - /app/node_modules
      - ./:/app/src/main
    stdin_open: true
  mysql:
    container_name: mysql-container
    image: mysql
    ports:
      - "3406:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
